initial
tahackr/coin-tracker pull request #1
Opened 2023-08-20 16:01 UTC by tahackr

2023-08-20 16:27 UTC, Zoz-trk requested changes
- [ ] Please review comments and refactor necessary parts.
- [ ] Separation of concerns are key in React folder structure. Try creating relevant folders or files when necessary.
- [ ] Create json file for mock data to be used in your fetch request so that you wont have to work with static inputs in your components.
- [ ] Ignore api configurations for now until you create first version of UI with mock data.

2023-08-20 16:27 UTC, Zoz-trk commented on src/App.js
> +    return <Table />;
- [x] App Component should preserve its default rendering stage as you shown in this example.
- [ ] One improvement could be adding container and wrapping sub components inside this wrapper for every other component that will be rendered on the page so that you could easily follow separation of concerns paradigm.

2023-08-20 16:27 UTC, Zoz-trk commented on src/components/Table.js
> +    const data = useFetch("v1/cryptocurrency/listings/latest");
- [ ] Destructuring response and renaming response data semantically would help with readability and maintainability of data.

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +            setCoins(data);
- [ ] How do you know if data is returned without any issue ?

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +    (async function () {
- [ ] What`s the best practice when fetching the data in React.js ? Should we use immediately invoked functions as you did or something else ?

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +    console.log(url);
- [ ] Clean all the console.log`s from your PR`s

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +                headers: {
- [ ] Instead of manipulating headers directly and adding keys in your request, please save necessary informations into .env file.

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +    })();
- [ ] Main purpose of creating useFetch hook is reusability. Do you think we can use this hook anywhere else in our application ?

2023-08-20 16:27 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +    const [coins, setCoins] = React.useState(null);
- [ ] What`s your plan to handle loading and error stages ? Currently, I don`t see any loading indicator. Also, there is only a single console log statement for error stage which is anti-pattern in React applications.

2023-08-20 16:27 UTC, Zoz-trk commented on tailwind.config.js
> +    content: ["./src/**/*.{html,js}"],
- [ ] Are you able to see Tailwind styles being applied to the page ?

2023-08-20 16:27 UTC, Zoz-trk commented on src/components/Table.js
> +        <table className="block table-fixed p-16">
- [ ] Are you sure you would like to go with Native Table component ? You can try Material Ui and I believe it will be more sustainable in the long rung.

2023-08-20 18:35 UTC, tahackr commented on src/components/Table.js
> +        <table className="block table-fixed p-16">
Instead of using a Native Table component, I have implemented a Material UI Table component.

2023-08-20 18:36 UTC, tahackr commented on tailwind.config.js
> +    content: ["./src/**/*.{html,js}"],
Yes, I am.

2023-08-20 18:37 UTC, tahackr commented on src/hooks/use-fetch.js
> +    const [coins, setCoins] = React.useState(null);
I have restructured the use-fetch hook in order to handle fetching and error statuses.

2023-08-20 18:38 UTC, tahackr commented on src/hooks/use-fetch.js
> +    })();
I have restructured it to be reusable.

2023-08-20 18:43 UTC, tahackr commented on src/hooks/use-fetch.js
> +                headers: {
I am having issues with creating an .env file. Webpack version 5 does not support "dotenv" package.Following the instructions Webpack gave, I installed a few more packages and created "resolve.fallback" object in the webpack.config file.Even though I don't get any errors now, importing dotenv/config does not create a process object therefore trying to access it breaks the code.

2023-08-20 18:45 UTC, tahackr commented on src/hooks/use-fetch.js
> +    (async function () {
I have made use of "useEffect" hook and moved my function into it.

2023-08-20 18:48 UTC, tahackr commented on src/App.js
> +    return <Table />;
I have wrapped the newly implemented Material UI Table component into a div.

2023-08-20 18:53 UTC, tahackr commented on src/components/Table.js
> +    const data = useFetch("v1/cryptocurrency/listings/latest");
I have destructured the data I get from "useFetch" hook. Hook returns an object with data,isFetching,error properties.I am not making use of isFetching and data right now. After fixing the issue with http requests I will make use of the data, for isFetching, I can make a Skeleton component to use during fetching if requested.

2023-08-20 18:57 UTC, tahackr commented on src/hooks/use-fetch.js
> +            setCoins(data);
I have wrapped setting the data state into an if block. But I wanted to ask, wouldn't try block throw an error and therefore stopping the execution if http request fails?

2023-08-20 21:03 UTC, Zoz-trk commented on src/components/Table.js
> +        data: deneme,
- [ ] Always make sure that you use semantic naming conventions for your variables. "Deneme" is not one of them.

2023-08-20 21:04 UTC, Zoz-trk commented on src/components/TableBodyRow.js
> +            <th className="text-left">{data.name}</th>
- [ ] Its better to destructure data object before you use any properties of it.

2023-08-20 21:07 UTC, Zoz-trk requested changes

2023-08-20 21:07 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +import * as React from "react";
- [ ] Directly import necessary React hooks. It will improve readibility.

2023-08-20 21:07 UTC, Zoz-trk commented on src/index.css
> +body {
- [ ] Why do you need styling properties in index.css file ? Either use tailwind as inline styling or prefer Material UI way of doing themes.

2023-08-20 21:11 UTC, Zoz-trk requested changes

2023-08-20 21:11 UTC, Zoz-trk commented on src/components/Table.js
> +function Table() {
- [ ] You should move mock data into its own folder. It could be a folder under src directory named "data" and under data folder you may have a file like mockData.json.

2023-08-20 21:11 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +                if (data) {
- [ ] response data is object and you need a way of verifying if response is ok. Check possible return values of get requests.

2023-08-20 21:14 UTC, Zoz-trk commented on src/hooks/use-fetch.js
> +            setCoins(data);
Catch would grab most of the errors but there are some others which should be verified right after fetch process. I`d suggest making research on this topic. Server or API`s doesn`t always return proper error states.

2023-08-20 21:29 UTC, tahackr commented on src/hooks/use-fetch.js
> +                if (data) {
Made these changes.

```
const { data, status } = await axios.get(url);

                if (status === 200) {
                    setData(data);
                }
```

2023-08-20 21:35 UTC, tahackr commented on src/hooks/use-fetch.js
> +import * as React from "react";
I have never imported it this way. Faced an error "React is not defined" when i was creating the extension and tried to import it like this.Fixed the error then.But now just tried to import it directly and I don't get the error anymore. 

TL;DR changed imports

2023-08-20 21:42 UTC, tahackr commented on src/components/TableBodyRow.js
> +            <th className="text-left">{data.name}</th>
Is it better to destructure the data in the props like this:
`function TableBodyRow({ data: { price, change, name } })`
or like this:
```
function TableBodyRow({ data })
const { price, change, name } = data;
```
The first one is less code but wanted to be sure about the conventions or readability issues if this cause any.

2023-08-20 22:10 UTC, tahackr commented on src/components/Table.js
> +function Table() {
I used "json-server" package in my earlier projects to learn more about http requests. Installed it and created a db.json file.

2023-08-21 03:32 UTC, Zoz-trk commented on src/components/TableBodyRow.js
> +            <th className="text-left">{data.name}</th>
I would prefer second option.

2023-08-21 03:34 UTC, Zoz-trk approved these changes

2023-08-21 03:35 UTC, Zoz-trk commented
Looks good to me therefore merging this PR.
We`ll work on further improvements later on.
Great job!

2023-08-21 03:35 UTC, merged